"""
Prompts module for the AI Assistant.
"""

from .system_prompt import (
    GENUI_SYSTEM_PROMPT,
    NO_DATA_PROMPT,
    DOCUMENT_ANALYSIS_PROMPT,
    COMPONENT_SCHEMA,
)

# Deprecated - kept for backwards compatibility
THESYS_SYSTEM_PROMPT = GENUI_SYSTEM_PROMPT
ASSISTANT_SYSTEM_PROMPT = GENUI_SYSTEM_PROMPT

__all__ = [
    "GENUI_SYSTEM_PROMPT",
    "NO_DATA_PROMPT",
    "DOCUMENT_ANALYSIS_PROMPT",
    "COMPONENT_SCHEMA",
    "THESYS_SYSTEM_PROMPT",
    "ASSISTANT_SYSTEM_PROMPT",
]
